added check for cg file before qc step

diff --git a/rr_p1/vcf_in/annovar_rr b/rr_p1/vcf_in/annovar_rr
--- a/rr_p1/vcf_in/annovar_rr
+++ b/rr_p1/vcf_in/annovar_rr
@@ -49,6 +49,10 @@ echo "filtering by cancer genes"
 bcftools filter -R ~/cg_v2.bed -o cg_filt.vcf.gz $vcf
 
 #QC
+if [ ! -f "cg_filt.vcf.gz" ]; then
+    echo "Error: cg_filt.vcf.gz not found in the current working directory."
+    exit 1
+fi
 
 if [[ "$mode" == "l" ]]; then
     echo "QC (Mode : Low)"
